version: 2.1

orbs:
  docker: circleci/docker@2.8.2

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/app
    steps:
      - checkout

      - docker/build:
          image: "$DOCKERHUB_USERNAME/node-js-sample"
          dockerfile: Dockerfile
          tag: "0.1.${CIRCLE_BUILD_NUM}"

      - run:
          name: Forcer le login Docker
          command: echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      - docker/push:
          image: "$DOCKERHUB_USERNAME/node-js-sample"
          tag: "0.1.${CIRCLE_BUILD_NUM}"
