version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            # Exemple : versionner l'image avec le numéro de build
            TAG=0.1.$CIRCLE_BUILD_NUM
            docker build -t $DOCKERHUB_USERNAME/node-js-sample:$TAG .
      - run:
          name: Push Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_USERNAME/node-js-sample:$TAG